# This workflow will build and upload the Python Package using Twine when a release is created

name: Release and Deploy Python Package

# When a tagged commit is pushed to master
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:


jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - uses: actions/cache@v2
      with:
        key: v0-${{ runner.os }}-pip-lint-${{ hashFiles('setup.cfg') }}
        path: ~/.cache/pip
        restore-keys: |
          v0-${{ runner.os }}-pip-lint-
          v0-${{ runner.os }}-pip-

    - name: Install latest pip, setuptools, twine + wheel
      run: |
        python -m pip install --upgrade pip
        pip install setuptools twine wheel

    - name: Build wheels
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish package with twine
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload --verbose dist/*

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*
