# This workflow will build and upload the Python Package using Twine when a release is created

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    name: PyPI Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install latest pip, setuptools, twine + wheel
      run: |
        python -m pip install --upgrade pip setuptools twine wheel

    - name: Build wheels
      run: |
        python setup.py bdist_wheel
        python setup.py sdist

    - name: Publish package with twine
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload --verbose -u '__token__' dist/*